name: Nightly
on:
  schedule:
    - cron: '00 23 * * *'
jobs:
  nightly:
    uses: mullvad/rsw-public/.github/workflows/go-ci.yaml@master
    with:
      govulncheck-ignore-error: true
      govulncheck-go: 'go1.22.4'
